/* 
 * Copyright (C) 2017 Alejandro Hernández Ferrero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package testb;

import javax.swing.tree.MutableTreeNode;
import libqew.StackPanel;
import libqew.TabsPanel;
import utils.Messenger;
import utils.Messenger.MessageReceiver;

/**
 *
 * @author Alejandro Hernández Ferrero
 */
public class TreeView extends libqew.TreeViewPanel {

    /**
     * Creates new form TreeView
     */
    public TreeView() {
        initComponents();
        Messenger.addListener("Eliminar", new MessageReceiver() {
                          @Override
                          public void receive(Object key, Object message) {
                              MutableTreeNode seleccionado = getSelectedNode();
                              if (seleccionado != null) {
                                  remove(seleccionado);
                              }
                          }
                      });
        Messenger.addListener("Insertar", new MessageReceiver() {
                          @Override
                          public void receive(Object key, Object message) {
                              String[] mensaje = (String[]) message;
                              String tipo = mensaje[0];
                              PanelBase panelBase = new PanelBase();
                              panelBase.setName(mensaje[1]);
                              MutableTreeNode nodo = getSelectedNode();
                              if (nodo == null) {
                                  nodo = getRoot();
                              }
                              switch (tipo) {
                                  case "Node":
                                      insertIntoNode(panelBase, nodo);
                                      break;
                                  case "StackPanel":
                                      StackPanel stack;
                                      if (getSelectedComponent() instanceof StackPanel) {
                                          stack = (StackPanel) getSelectedComponent();
                                      } else {
                                          stack = new StackPanel(getSelectedComponent());
                                      }
                                      stack.addChild(panelBase);
                                      nodo.setUserObject(stack);
                                      break;
                                  case "TabsPanel":
                                      TabsPanel tabs;
                                      if (getSelectedComponent() instanceof TabsPanel) {
                                          tabs = (TabsPanel) getSelectedComponent();
                                      } else {
                                          tabs = new TabsPanel(getSelectedComponent());
                                      }
                                      tabs.addChild(panelBase);
                                      nodo.setUserObject(tabs);
                                      break;
                              }
                          }
                      });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
    }
    // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
